# Generated by Django 5.1.6 on 2025-09-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_id', models.CharField(max_length=100, unique=True)),
                ('hash_value', models.CharField(max_length=256)),
                ('issuer', models.CharField(max_length=200)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
